// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhakhoa.Data;

#nullable disable

namespace Nhakhoa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527101334_AddSpecialtyAndClinicSystem")]
    partial class AddSpecialtyAndClinicSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhakhoa.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Nhakhoa.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultSpecialtyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DefaultSpecialtyId");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 15,
                            DefaultSpecialtyId = 1,
                            IsActive = true,
                            Location = "Tầng 1 - Khu A",
                            Name = "Phòng khám Tim mạch A1",
                            UpdatedAt = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10,
                            DefaultSpecialtyId = 2,
                            IsActive = true,
                            Location = "Tầng 2 - Khu B",
                            Name = "Phòng khám Thần kinh B2",
                            UpdatedAt = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 20,
                            DefaultSpecialtyId = 4,
                            IsActive = true,
                            Location = "Tầng 1 - Khu C",
                            Name = "Phòng khám Răng Hàm Mặt C1",
                            UpdatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Nhakhoa.Models.DoctorSpecialty", b =>
                {
                    b.Property<int>("StaffProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("StaffProfileId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("DoctorSpecialties");

                    b.HasData(
                        new
                        {
                            StaffProfileId = 204,
                            SpecialtyId = 1
                        },
                        new
                        {
                            StaffProfileId = 203,
                            SpecialtyId = 2
                        });
                });

            modelBuilder.Entity("Nhakhoa.Models.MedicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("MedicalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Nội tổng quát",
                            Description = "Khám sàng lọc và tư vấn sức khỏe cơ bản",
                            IsActive = true,
                            Name = "Khám nội tổng quát",
                            Price = 500000m,
                            SpecialtyId = 1,
                            UpdatedAt = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Department = "Xét nghiệm",
                            Description = "Phân tích huyết học tự động công nghệ cao",
                            IsActive = true,
                            Name = "Xét nghiệm công thức máu (24 chỉ số)",
                            Price = 150000m,
                            SpecialtyId = 3,
                            UpdatedAt = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Department = "Chẩn đoán hình ảnh",
                            Description = "Siêu âm 4D ổ bụng và các cơ quan nội tạng",
                            IsActive = false,
                            Name = "Siêu âm bụng tổng quát",
                            Price = 350000m,
                            SpecialtyId = 2,
                            UpdatedAt = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Department = "Nha khoa tổng quát",
                            Description = "Nhổ răng khôn mọc lệch, mọc ngầm sử dụng sóng siêu âm Piezotome",
                            IsActive = true,
                            Name = "Nhổ răng khôn",
                            Price = 1200000m,
                            SpecialtyId = 4,
                            UpdatedAt = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Department = "Nha khoa thẩm mỹ",
                            Description = "Tẩy trắng răng công nghệ Laser Whitening nhanh chóng, không ê buốt",
                            IsActive = true,
                            Name = "Tẩy trắng răng Laser",
                            Price = 2500000m,
                            SpecialtyId = 4,
                            UpdatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Nhakhoa.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleIcon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAllowed = true,
                            ModuleIcon = "bi-person-lock",
                            ModuleKey = "account_rbac",
                            ModuleName = "Quản lý tài khoản & RBAC",
                            Role = "Admin",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsAllowed = true,
                            ModuleIcon = "bi-journal-check",
                            ModuleKey = "audit_log",
                            ModuleName = "Audit log & báo cáo hệ thống",
                            Role = "Admin",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsAllowed = true,
                            ModuleIcon = "bi-gear",
                            ModuleKey = "system_config",
                            ModuleName = "Cấu hình hệ thống",
                            Role = "Admin",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsAllowed = true,
                            ModuleIcon = "bi-file-medical",
                            ModuleKey = "emr",
                            ModuleName = "Bệnh án điện tử (EMR)",
                            Role = "Admin",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IsAllowed = true,
                            ModuleIcon = "bi-capsule",
                            ModuleKey = "prescription",
                            ModuleName = "Kê đơn thuốc",
                            Role = "Admin",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IsAllowed = true,
                            ModuleIcon = "bi-eyedropper",
                            ModuleKey = "lab_test",
                            ModuleName = "Chỉ định & kết quả xét nghiệm",
                            Role = "Admin",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            IsAllowed = true,
                            ModuleIcon = "bi-calendar-event",
                            ModuleKey = "schedule_view",
                            ModuleName = "Lịch khám cá nhân (read)",
                            Role = "Admin",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            IsAllowed = true,
                            ModuleIcon = "bi-calendar-check",
                            ModuleKey = "appointment",
                            ModuleName = "Quản lý lịch hẹn",
                            Role = "Admin",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            IsAllowed = true,
                            ModuleIcon = "bi-person-plus",
                            ModuleKey = "patient_reg",
                            ModuleName = "Đăng ký / tìm kiếm bệnh nhân",
                            Role = "Admin",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            IsAllowed = true,
                            ModuleIcon = "bi-receipt",
                            ModuleKey = "invoice",
                            ModuleName = "Tạo hóa đơn & thu tiền",
                            Role = "Admin",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            IsAllowed = true,
                            ModuleIcon = "bi-clipboard2-data",
                            ModuleKey = "patient_admin",
                            ModuleName = "Thông tin hành chính bệnh nhân",
                            Role = "Admin",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            IsAllowed = false,
                            ModuleIcon = "bi-person-lock",
                            ModuleKey = "account_rbac",
                            ModuleName = "Quản lý tài khoản & RBAC",
                            Role = "Doctor",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 13,
                            IsAllowed = false,
                            ModuleIcon = "bi-journal-check",
                            ModuleKey = "audit_log",
                            ModuleName = "Audit log & báo cáo hệ thống",
                            Role = "Doctor",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 14,
                            IsAllowed = false,
                            ModuleIcon = "bi-gear",
                            ModuleKey = "system_config",
                            ModuleName = "Cấu hình hệ thống",
                            Role = "Doctor",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 15,
                            IsAllowed = true,
                            ModuleIcon = "bi-file-medical",
                            ModuleKey = "emr",
                            ModuleName = "Bệnh án điện tử (EMR)",
                            Role = "Doctor",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 16,
                            IsAllowed = true,
                            ModuleIcon = "bi-capsule",
                            ModuleKey = "prescription",
                            ModuleName = "Kê đơn thuốc",
                            Role = "Doctor",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 17,
                            IsAllowed = true,
                            ModuleIcon = "bi-eyedropper",
                            ModuleKey = "lab_test",
                            ModuleName = "Chỉ định & kết quả xét nghiệm",
                            Role = "Doctor",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 18,
                            IsAllowed = true,
                            ModuleIcon = "bi-calendar-event",
                            ModuleKey = "schedule_view",
                            ModuleName = "Lịch khám cá nhân (read)",
                            Role = "Doctor",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 19,
                            IsAllowed = false,
                            ModuleIcon = "bi-calendar-check",
                            ModuleKey = "appointment",
                            ModuleName = "Quản lý lịch hẹn",
                            Role = "Doctor",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 20,
                            IsAllowed = false,
                            ModuleIcon = "bi-person-plus",
                            ModuleKey = "patient_reg",
                            ModuleName = "Đăng ký / tìm kiếm bệnh nhân",
                            Role = "Doctor",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 21,
                            IsAllowed = false,
                            ModuleIcon = "bi-receipt",
                            ModuleKey = "invoice",
                            ModuleName = "Tạo hóa đơn & thu tiền",
                            Role = "Doctor",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 22,
                            IsAllowed = false,
                            ModuleIcon = "bi-clipboard2-data",
                            ModuleKey = "patient_admin",
                            ModuleName = "Thông tin hành chính bệnh nhân",
                            Role = "Doctor",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 23,
                            IsAllowed = false,
                            ModuleIcon = "bi-person-lock",
                            ModuleKey = "account_rbac",
                            ModuleName = "Quản lý tài khoản & RBAC",
                            Role = "Receptionist",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            IsAllowed = false,
                            ModuleIcon = "bi-journal-check",
                            ModuleKey = "audit_log",
                            ModuleName = "Audit log & báo cáo hệ thống",
                            Role = "Receptionist",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            IsAllowed = false,
                            ModuleIcon = "bi-gear",
                            ModuleKey = "system_config",
                            ModuleName = "Cấu hình hệ thống",
                            Role = "Receptionist",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 26,
                            IsAllowed = false,
                            ModuleIcon = "bi-file-medical",
                            ModuleKey = "emr",
                            ModuleName = "Bệnh án điện tử (EMR)",
                            Role = "Receptionist",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 27,
                            IsAllowed = false,
                            ModuleIcon = "bi-capsule",
                            ModuleKey = "prescription",
                            ModuleName = "Kê đơn thuốc",
                            Role = "Receptionist",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 28,
                            IsAllowed = false,
                            ModuleIcon = "bi-eyedropper",
                            ModuleKey = "lab_test",
                            ModuleName = "Chỉ định & kết quả xét nghiệm",
                            Role = "Receptionist",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 29,
                            IsAllowed = false,
                            ModuleIcon = "bi-calendar-event",
                            ModuleKey = "schedule_view",
                            ModuleName = "Lịch khám cá nhân (read)",
                            Role = "Receptionist",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 30,
                            IsAllowed = true,
                            ModuleIcon = "bi-calendar-check",
                            ModuleKey = "appointment",
                            ModuleName = "Quản lý lịch hẹn",
                            Role = "Receptionist",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 31,
                            IsAllowed = true,
                            ModuleIcon = "bi-person-plus",
                            ModuleKey = "patient_reg",
                            ModuleName = "Đăng ký / tìm kiếm bệnh nhân",
                            Role = "Receptionist",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 32,
                            IsAllowed = true,
                            ModuleIcon = "bi-receipt",
                            ModuleKey = "invoice",
                            ModuleName = "Tạo hóa đơn & thu tiền",
                            Role = "Receptionist",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 33,
                            IsAllowed = true,
                            ModuleIcon = "bi-clipboard2-data",
                            ModuleKey = "patient_admin",
                            ModuleName = "Thông tin hành chính bệnh nhân",
                            Role = "Receptionist",
                            SortOrder = 11
                        });
                });

            modelBuilder.Entity("Nhakhoa.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("StaffProfileId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            IsActive = true,
                            ShiftDate = new DateTime(2026, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StaffProfileId = 204
                        });
                });

            modelBuilder.Entity("Nhakhoa.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CARD-001",
                            Description = "Chuyên chẩn đoán và điều trị các bệnh lý tim mạch và mạch máu.",
                            Name = "Tim mạch",
                            UpdatedAt = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Code = "NEUR-002",
                            Description = "Điều trị các bệnh lý liên quan đến hệ thần kinh trung ương và ngoại biên.",
                            Name = "Thần kinh",
                            UpdatedAt = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Code = "PEDI-003",
                            Description = "Chăm sóc sức khỏe toàn diện, sàng lọc phát triển thể chất ở trẻ em.",
                            Name = "Nhi khoa",
                            UpdatedAt = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Code = "DENT-004",
                            Description = "Điều trị và phục hình răng hàm mặt thẩm mỹ, công nghệ cao.",
                            Name = "Răng Hàm Mặt",
                            UpdatedAt = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Nhakhoa.Models.StaffProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryClinic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffProfiles");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Address = "Hà Nội",
                            Department = "Nội tổng quát",
                            Gender = "Nam",
                            JoinDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionTitle = "Y học cổ truyền",
                            PrimaryClinic = "Phòng khám A1",
                            StaffCode = "DOC-102",
                            UserId = 201
                        },
                        new
                        {
                            Id = 202,
                            Address = "Đà Nẵng",
                            Department = "Chẩn đoán hình ảnh",
                            Gender = "Nữ",
                            JoinDate = new DateTime(2021, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionTitle = "Chẩn đoán hình ảnh",
                            PrimaryClinic = "Phòng B2",
                            StaffCode = "DOC-205",
                            UserId = 202
                        },
                        new
                        {
                            Id = 203,
                            Address = "Hồ Chí Minh",
                            Department = "Thần kinh",
                            Gender = "Nam",
                            JoinDate = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionTitle = "Thần kinh học",
                            PrimaryClinic = "Phòng C1",
                            StaffCode = "DOC-098",
                            UserId = 203
                        },
                        new
                        {
                            Id = 204,
                            Address = "Hà Nội",
                            Department = "Tim mạch",
                            Gender = "Nữ",
                            JoinDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionTitle = "Chuyên gia Tim mạch",
                            PrimaryClinic = "Phòng khám A1",
                            StaffCode = "DOC-110",
                            UserId = 204
                        });
                });

            modelBuilder.Entity("Nhakhoa.Models.StaffQualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicDegree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AcademicRank")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StaffQualifications");
                });

            modelBuilder.Entity("Nhakhoa.Models.StaffSalaryInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DegreeMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("DegreeTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MonthlyBonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RankMultiplier")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RankTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SeniorityAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpecializationAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaffSalaryInfos");
                });

            modelBuilder.Entity("Nhakhoa.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemporaryPassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ResetOtpCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("ResetOtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@clinic.com",
                            FullName = "Admin System",
                            IsActive = true,
                            IsTemporaryPassword = false,
                            PasswordHash = "admin",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            SecurityStamp = "default-admin-security-stamp",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 201,
                            Email = "dat.nguyen@clinic.com",
                            FullName = "BS. Nguyễn Văn Đạt",
                            IsActive = true,
                            IsTemporaryPassword = false,
                            PasswordHash = "123456",
                            PhoneNumber = "0987654321",
                            Role = "Doctor",
                            SecurityStamp = "doctor-1-security-stamp",
                            Username = "doctor1"
                        },
                        new
                        {
                            Id = 202,
                            Email = "mai.tran@clinic.com",
                            FullName = "BS. Trần Thanh Mai",
                            IsActive = false,
                            IsTemporaryPassword = false,
                            PasswordHash = "123456",
                            PhoneNumber = "0987654322",
                            Role = "Doctor",
                            SecurityStamp = "doctor-2-security-stamp",
                            Username = "doctor2"
                        },
                        new
                        {
                            Id = 203,
                            Email = "tuan.le@clinic.com",
                            FullName = "BS. Lê Anh Tuấn",
                            IsActive = true,
                            IsTemporaryPassword = false,
                            PasswordHash = "123456",
                            PhoneNumber = "0987654323",
                            Role = "Doctor",
                            SecurityStamp = "doctor-3-security-stamp",
                            Username = "doctor3"
                        },
                        new
                        {
                            Id = 204,
                            Email = "sarah.johnson@clinic.com",
                            FullName = "BS. Sarah Johnson",
                            IsActive = true,
                            IsTemporaryPassword = false,
                            PasswordHash = "123456",
                            PhoneNumber = "0987654324",
                            Role = "Doctor",
                            SecurityStamp = "doctor-4-security-stamp",
                            Username = "doctor4"
                        });
                });

            modelBuilder.Entity("Nhakhoa.Models.Clinic", b =>
                {
                    b.HasOne("Nhakhoa.Models.Specialty", "DefaultSpecialty")
                        .WithMany("Clinics")
                        .HasForeignKey("DefaultSpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultSpecialty");
                });

            modelBuilder.Entity("Nhakhoa.Models.DoctorSpecialty", b =>
                {
                    b.HasOne("Nhakhoa.Models.Specialty", "Specialty")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhakhoa.Models.StaffProfile", "StaffProfile")
                        .WithMany("DoctorSpecialties")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("Nhakhoa.Models.MedicalService", b =>
                {
                    b.HasOne("Nhakhoa.Models.Specialty", "Specialty")
                        .WithMany("MedicalServices")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Nhakhoa.Models.Shift", b =>
                {
                    b.HasOne("Nhakhoa.Models.Clinic", "Clinic")
                        .WithMany("Shifts")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nhakhoa.Models.StaffProfile", "StaffProfile")
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("Nhakhoa.Models.StaffProfile", b =>
                {
                    b.HasOne("Nhakhoa.Models.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("Nhakhoa.Models.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nhakhoa.Models.StaffQualification", b =>
                {
                    b.HasOne("Nhakhoa.Models.User", "User")
                        .WithMany("StaffQualifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nhakhoa.Models.StaffSalaryInfo", b =>
                {
                    b.HasOne("Nhakhoa.Models.User", "User")
                        .WithOne("StaffSalaryInfo")
                        .HasForeignKey("Nhakhoa.Models.StaffSalaryInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nhakhoa.Models.Clinic", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Nhakhoa.Models.Specialty", b =>
                {
                    b.Navigation("Clinics");

                    b.Navigation("DoctorSpecialties");

                    b.Navigation("MedicalServices");
                });

            modelBuilder.Entity("Nhakhoa.Models.StaffProfile", b =>
                {
                    b.Navigation("DoctorSpecialties");
                });

            modelBuilder.Entity("Nhakhoa.Models.User", b =>
                {
                    b.Navigation("StaffProfile")
                        .IsRequired();

                    b.Navigation("StaffQualifications");

                    b.Navigation("StaffSalaryInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
